### ISSUE TITLE
CSS formatting makes some links invisible in breadcrumb navigation

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/documentation#100]
Observing a minor css problem on https://mycroft.ai/documentation/skills/skill-settings/ .  The navigation breadcrumb trail in the header has text color the same as the background when in a non-hovering state. This makes the element "invisible" until you hover over it. This was using Chrome. Also note: I visited a couple of other pages in Mycroft Documentation that did _not_ exhibit the issue, so it is probably not a master/global CSS issue.

**Comment by KathyReid** [comment]
Thanks for raising this @jrwarwick, I can replicate the issue you've reported. I dug into this about 6 months ago - there's some sort of conflict between the CSS I've used and the WordPress Theme we use - Salient - I remember I spent a couple hours trying to debug it but couldn't. Will come back around on it.

**Comment by krisgesling** [comment]
Hey, you may or may not have seen but we've switched to a new platform for our docs :grin: 

We therefore don't have this issue anymore, so will close this.
