### ISSUE TITLE
Clean up the "Introduction to writing skills" document

### ISSUE THREAD

**Issue by strugee** [MycroftAI/documentation#123]
It's full of outdated stuff. See https://github.com/MycroftAI/documentation/pull/121#issuecomment-508706385 and the ensuing conversation.

**Comment by krisgesling** [comment]
Hi AJ,

Thanks for the updates! There are many parts of the docs in need of updating. Mycroft moves quickly and it's hard to keep up. It's also one of those things that are constantly added to, however we also need to take the time to step back, rethink the structure and consider what should be removed as well.

I saw you mention that you are just getting started, but I think this is a really valuable perspective to bring as well. At times it can be harder for those very familiar with Mycroft to see what's missing or doesn't make sense to newcomers.

I'd love to hear any suggestions you have on a new structure for this section, and we can work from there on fleshing out and updating the content.

**Comment by krisgesling** [comment]
Hey, the Skill dev docs have received a fair bit of attention over the last year, so I'm going to close this for now. 

If there are new issues spotted please open a new issue and we can handle those.
