### ISSUE TITLE
Extend list of basic voice commands available

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/documentation#141]
We have a list of basic commands available in the default Mycroft Skills: 
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/basic-commands

This is a very short list with only one or two utterances per Skill. To help new users understand the range of functionality available, it would be great to extend this list to cover all major functions of each Skill.

To add to this list, just use a Mycroft Skill and document the utterances that are most useful to you. You can do this by cloning the repository, or editing the list directly in the browser:
https://github.com/MycroftAI/documentation/blob/master/docs/using-mycroft-ai/basic-commands.md

**Comment by 1Maxnet1** [comment]
I'll note me that issue and want to add, that e.g. "send me debug info" is not (anymore) in the basic commands. At least my Mycroft couldn't answer it after installation, also if I typed it in the CLI.

**Comment by krisgesling** [comment]
Thanks for the heads up Max. It does appear that it is no longer in the Support Skill so I've removed it for now.
