### ISSUE TITLE
Inform Skill authors that utterances are all lowercase

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/documentation#167]
Need to add in somewhere that all utterance data is received lowercase.

**Comment by stevavoliajvar** [comment]
Maybe [here](https://github.com/MycroftAI/documentation/blob/master/docs/skill-development/common-issues.md) ?

**Comment by krisgesling** [comment]
Yeah good suggestion, I've added it in there and included a link to where to get more help.

I'll also try and incorporate it into the intro to skill dev sometime but calling this done for now :)

Fixed by [dfa47df](https://github.com/MycroftAI/documentation/commit/dfa47df3316e81c2d59c4c309cce982f644c00f2)
