### ISSUE TITLE
Change self.emitter.emit to self.bus.emit in the docs for MessageBus Types

### ISSUE THREAD

**Issue by auwsom** [MycroftAI/documentation#174]
https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-types

Under the 'Generating Message from MycroftSkill' code tab. Change self.emitter.emit to self.bus.emit in the docs. Very confusing to try to get working..

Originally here:
https://github.com/MycroftAI/mycroft-core/issues/2611

**Comment by krisgesling** [comment]
Thanks auwsom!

I've updated the method to the new `self.bus.emit` and extended the examples to show what needs to be imported:
https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-bus#mycroftskill-interaction

**Comment by auwsom** [comment]
@krisgesling , thanks a ton!
