### ISSUE TITLE
Docbook documentation sample embedded html is missing closing head tag

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/documentation#219]
**Describe the bug**
Closing head tag in the "HTML raw example" of the Qt GUI section of the docbook docs:
https://mycroft-ai.gitbook.io/docs/skill-development/displaying-information/mycroft-gui#simple-template-based-text-and-image-skill-displays

Also, I would recommend a simpler and more modern doctype declaration and html attributes (i.e., the simpler boilerplate as described here:  http://html5doctor.com/html-5-boilerplates/ )

**To Reproduce**
1. Go to ['dockbook documentation, gui section'](https://mycroft-ai.gitbook.io/docs/skill-development/displaying-information/mycroft-gui#simple-template-based-text-and-image-skill-displays
)
2. scroll down to "HTML Raw Example"
3. See error opening head tag, but no closing head tag

**Expected behavior**
fully valid and modern html5 code embedded

**Comment by krisgesling** [comment]
Good spotting - I also didn't realise how much stuff you can cut out with HTML5 (_feeling old now..._)

I've greatly simplified it, but more importantly it's now valid markup :+1:
