### ISSUE TITLE
Relative link in MD is resolved in GH context when creating HTML page

### ISSUE THREAD

**Issue by ceich** [MycroftAI/documentation#225]
**Describe the bug**
My fix for #223 in #224 seemed reasonable, but when the MD was converted to HTML, the relative link was turned into:
> https://github.com/MycroftAI/documentation/blob/master/docs/using-mycroft-ai/customizations/wake-word/README.md#switching-wake-word-listeners

Instead of:
> https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/wake-word#switching-wake-word-listeners

**To Reproduce**
1. Use MD link syntax to target a relative link, e.g. `../sibling-folder/some-page#some-fragment`
2. Build HTML
3. Find that the relative link has been resolved in the GH context, not the target context
4. Clicking the link yields GH's 404 page

**Expected behavior**
The relative link is preserved in the conversion process.

**Comment by ceich** [comment]
Well, there are plenty of relative links in the source, but they all:
1. Add the `.md` extension
2. Do not include a fragment/anchor

So one of these is likely the culprit in the case of #224.

**Comment by krisgesling** [comment]
Closed by #226
