### ISSUE TITLE
Outdated (404) link to https://mycroft.ai/to/mark-ii-stable

### ISSUE THREAD

**Issue by rmsppu** [MycroftAI/documentation#227]
The page https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/mark-ii contains:

> Download the latest version of the Mark II operating system from:
> https://mycroft.ai/to/mark-ii-stable

​​The link is broken.

**Comment by krisgesling** [comment]
Hi thanks for flagging this - the redirect on that url got nixed accidentally. 

I've added a new link to [the docs](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/mark-ii/mark-ii-dev-kit#software) for the stable version that came with the Dev Kits but this is very different to what is shipping on the production Mark II's:
https://mycroft.ai/to/mark-ii-dev-kit-stable

We should have the new stable that's being distributed on the production Mark II's available for download very shortly. That will get added to the new Mark II docs at: 
https://mycroft-ai.gitbook.io/mark-ii/

It can also be used on any Mark II Dev Kits.
