### ISSUE TITLE
Formatting and a few specifying words for more clarity in: Add a Git submodule for your Skill

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/documentation#43]
Partial extension of #3 : My first read of [Add a Git submodule for your Skill](https://mycroft.ai/documentation/skills/skill-submission/#add-a-git-submodule-for-your-skill) made me think I was supposed to execute the command "mycroft-skills" which _is_ a valid executable name! I therefore recommend two things:

1. make sure the "mycroft-skills" (in monotype) is inline, not on next line, 
2. give it preceding and following queue words and punctuation. 

So something like:  
Next we need to add the Submodule for your *Skill* to the `mycroft-skills` repository. For more help on Submodules in GitHub, feel free to check out this guide

Or, type the following git command in the terminal, assuming you are in the directory where you cloned the `mycroft-skills` repository:

`git submodule add $remote $name-your-skill`

where $remote is the git address for your repo [example]

**Comment by krisgesling** [comment]
Closing as we strongly recommend that people use MSK for submitting Skills now.
