### ISSUE TITLE
Skill Settings - details on method call argument options

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/documentation#45]
Under [How do I use skill settings](https://mycroft.ai/documentation/skills/skill-settings/#how-do-i-use-skill-settings) we see an example of calling self.settings.get() method with a single argument. However, later, pianobar-skill is cited as an exemplar, and it makes a method call with a second argument of an empty string, with no apparent explanation. Moreover, the autogenerated API seems to lack docstrings that would explain the optional arguments. Therefore, I am recommending not only an enhancement here in docs-rewrite, but also that it would spawn an edit/update to the core source such that API auto-gen docs would yield an overview on settings.get() method and its calling arguments.

**Comment by krisgesling** [comment]
This page got a good update including detailing the optional argument to the `.get()` method
https://mycroft-ai.gitbook.io/docs/skill-development/skill-structure/skill-settings

Closing (but re-open if I've missed something).
