### ISSUE TITLE
Skill publishing procedure suggests incorrect Github repository

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/documentation#46]
Skill publishing documentation found at:  https://mycroft.ai/documentation/skills/skill-submission/#submit-a-pr-pull-request-in-github-to-have-your-skill-listed

Is describing how to ultimately make edits to the Mycroft project public skills repository. It looks like there is an error here. Instructions say ", go to the GitHub repo for your Skill. Click the 'New Pull Request' button as shown in the image below" . But in this case, don't we actually want to create a pull request between our fork of the mycroft-skills repository (instead of our skill)? Isn't that where we would be making publishing details changes?

Note that the screenshot of a sample skill repo also (consistent with the instructions) is not correct.

**Comment by krisgesling** [comment]
Outdated due to new submission process:
https://mycroft-ai.gitbook.io/docs/skill-development/marketplace-submission/skills-acceptance-process

Closing.
