### ISSUE TITLE
Skill publishing procedure - initial steps regarding upstream repository

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/documentation#47]
Section [Add a Git submodule for your Skill](https://mycroft.ai/documentation/skills/skill-submission/#add-a-git-submodule-for-your-skill) of "Preparing your Skill for submission to the Mycroft Skills Repo" speaks of having cloned the mycroft-skills repo in the past tense. I recommend a small paragraph that spells that out in a little more detail. Maybe under its own heading immediately before this section.

Also, this would be an opportunity to describe the preferred repo and branch usage and naming. I.e.,:
 - Should we clone https://github.com/MycroftAI/mycroft-skills  directly to local working copy? Or should we first make our own fork of the repo?
 - should we work on private master branch? Or should we create a branch and make changes to the branch? If so, what is the preferred naming scheme? e.g., add-skill-name  or feature/skill-name  or public-skill-username-skill-name, etc
  Further down the page, in bullet point three of [Submit a PR (Pull Request) in GitHub to have your Skill listed](https://mycroft.ai/documentation/skills/skill-submission/#submit-a-pr-pull-request-in-github-to-have-your-skill-listed) , the implicit assumption appears to be no new branch, and the submitter would issue PR from their private fork's master branch:  "This will usually be MycroftAI/mycroft-skills/master and YourGitHubUsername/mycroft-skills/master"

**Comment by krisgesling** [comment]
Outdated due to new submission process:
https://mycroft-ai.gitbook.io/docs/skill-development/marketplace-submission/skills-acceptance-process

Closing.
