### ISSUE TITLE
"git clone" skills not working as stated in documentation on "Developing a new Skill"

### ISSUE THREAD

**Issue by f-e-l-i-x** [MycroftAI/documentation#65]
In the documentation for "Developing a new Skill" 
(link https://mycroft.ai/documentation/skills/introduction-developing-skills/)

it is stated

'
Then,
git clone
the repo you've just forked to your local machine.

For example, if your GitHub username is "JaneBloggs" then you will need to
git clone
from https://github.com/JaneBloggs/mycroft-skills.git
$ git clone https://github.com/JaneBloggs/mycroft-skills.git
'

However, I cannot clone the entire skills repository like this, I only end up with empty directories locally. The only way I can clone the skills is to clone the skills individually.

**Comment by krisgesling** [comment]
Outdated due to new submission process with MSK:
https://mycroft-ai.gitbook.io/docs/skill-development/marketplace-submission/skills-acceptance-process

Closing.
