### ISSUE TITLE
Messagebus table extends over page width, non-scrollable

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/documentation#78]
Received via feedback on the page; 

```
Hello,

A new rating #119 by "Anonymous" has been approved.

Date: July 11, 2018, 6:39pm

Comment: I am using Firefox and the table on this page does not fix the screen and I don\'t get a scroll bar to see the parts off the screen. Must be part of some css.
Overall Rating: 60%	
Documentation ratings: Average - sections are outdated or need clarification 

Thank you.

```

This issue was validated, screenshot below; 
![screenshot from 2018-07-13 01-50-26](https://user-images.githubusercontent.com/114158/42644769-b98d6b34-863f-11e8-8f44-b7c47a4d80ce.png)

----

Had a quick look - the MarkDown to HTML formatting simply uses the `<table>` and related tags - here are no `class` or `id` attributes added which would be useful for CSS styling. Possible approach here is to use more specific selectors to `word-wrap` within `<td>` elements. Posting as an Issue because I don't have time to fix right now.

**Comment by KathyReid** [comment]
Got another feedback on this one - it's clearly bugging people. 
Will bump this up the priority list. 

```
Hello,

A new rating #126 by "Anonymous" has been approved.

Date: August 17, 2018, 12:57pm

Comment: The table should allow the columns to wrap so the complete table is visible on a smaller display.
Also in the \'Connecting message handlers\', the last comment should have \'when active listening ends\'.
Overall Rating: 60%	
Documentation ratings: Average - sections are outdated or need clarification 

Thank you.
```

**Comment by krisgesling** [comment]
This has moved to a new format that is more responsive. 

Closing.
